### PR TITLE
Fix hint lifts, enable more tests

### PR DESCRIPTION
**Pull request by yrp604**
Somewhat obnoxiously, the manual does not list certain aliases. For
example, `hint #0` is `nop`. This means two things:
1. When I lifted the hint variants, I assumed they were different
   instructions, and so I lifted them separately.
2. When the lifter was processing them, the hints _without_ dedicated
   decode enums (e.g. `hint #6`) would work, while hints that _had_
   decoded variants (e.g. `hint #10` or `ARM64_ESB`) would not work, as
   that lifting case would not be hit. This caused some tests to not
   work.

This patch fixes tests for all hints by properly using the right
disassembler constants, and deletes the now-redundant intrinsics.

As a result of this, `sevl`, `esb`, `psbcsync`, and `yield` are now actually
lifted, instead of having code that would never be called to lift them.

### CODE REVIEW

**Comment by yrp604** [comment]
Things to note:
- Sorry about the churn
- the `nop` testcase is the empty string -- does LLIL_NOP get removed in the testing code?
- do you want debug warning logs in the should-be-unreachable hint cases? I left them as insurance against disassembler changes, but that kind of speculative coding can also be a source of bugs. I don't have strong feelings, but figured someone else might.
- net -2 lines of code resulting in 3 more instructions being lifted :)

**Comment by lwerdna** [comment]
> the nop testcase is the empty string -- does LLIL_NOP get removed in the testing code?

Yes, it gets "optimized" out between lifted IL and low level IL, which we retrieve in test.py with the line `for block in bv.functions[0].low_level_il: ...` in function `instr_to_il()`. The function's a hack, just take a look: it appends a return instruction, calls `bv.add_function()` then tries to retrieve the LLIL for the temporary function.

**Comment by lwerdna** [comment]
> Sorry about the churn

Thank you for the churn! Seriously! I should get these in over the weekend.

**Comment by lwerdna** [comment]
Great! Thanks for updating the tests and the verbose comments in il.cpp.

**Pull request merged**
