### PR TITLE
Lift umull instruction

### PR DESCRIPTION
**Pull request by brinlyau**
* Not sure if this is right

Would appreciate another set of eyes. 
http://shell-storm.org/armv8-a/ISA_v85A_A64_xml_00bet8_OPT/from-ISA_v85A_A64_xml_00bet8/umull_advsimd_vec.html

### CODE REVIEW

**Comment by yrp604** [comment]
I've been using this reference manual: https://developer.arm.com/docs/ddi0596/h/base-instructions-alphabetic-order/umull-unsigned-multiply-long-an-alias-of-umaddl -- it doesn't mention vectors and might be clearer than that one?

I think you'd want to use `REGSZ(operand1)` instead of the constant 8, and `REG(operand1)` instead of `ILREG` (basing it on the `ARM64_MUL` lift. This would make it identical to `MUL`, which makes me question if I'm missing something. As far as I can tell, `UMULL` is just two 32bit registers multiplied together and stored in a 64bit dst, while MUL is two 32 or 64 bit registers multiplied together stored in a 32 or 64bit dest, respectively. Should these have the same lift?

While you're here maybe do `UMADDL` too? Should be the same thing, except with an additional add on `operand4`.

**Comment by lwerdna** [comment]
@yrp604 

> This would make it identical to MUL, which makes me question if I'm missing something. As far as I can tell, UMULL is just two 32bit registers multiplied together and stored in a 64bit dst, while MUL is two 32 or 64 bit registers multiplied together stored in a 32 or 64bit dest, respectively. Should these have the same lift?

A question I shared, and whose answer required some research. The important characteristics are the result size in relation to the input size, and whether signed or unsigned.

UMULL expands the width (64-bit result from 32-bit inputs) and unsigned.
SMULL expands the width (64-bit result from 32-bit inputs) and signed.
MUL maintains the width (32-bit result from 32-bit inputs or 64-bit result from 64-bit inputs) and the signage is unspecified.

@rssor provided some clarity on why width-maintaining multiplies don't need to specify sign: because whatever nonsense is introduced by treating a possible sign bit as a factor bit get discarded anyways. Two signed 32-bit inputs to a MUL would have errors way above the bits b31...b0 in the result.

The IL instructions corresponding to UMULL/SMULL/MUL are IL_MULU_DP/IL_MULS_DP/IL_MUL.

I'll lift a few of the related instructions now (maybe UMADDL too which you suggested) which will hopefully serve as examples for the future.

**Comment by lwerdna** [comment]
@brinlyau Thanks as usual for the code! Please use tabs instead of spaces (only because that's the convention that occurs in il.cpp) and add a test atop arm64test.py in the future.

**Comment by lwerdna** [comment]
> I think you'd want to use REGSZ(operand1) instead of the constant 8, and REG(operand1) instead of ILREG (basing it on the ARM64_MUL lift.

It may be possible to get away with the 8 this time, since the spec says its always `umull x?, w?, w?`:

> Unsigned Multiply Long multiplies two 32-bit register values, and writes the result to the 64-bit destination register.

**Comment by yrp604** [comment]
Awesome, my general approach for lifting things has been to find the most similar instruction and then modify it for any differences so more instructions to use as a template is always great. Thanks for the details, all makes sense.

**Pull request merged**
