### PR TITLE
Lift wfi/wfe intrinsic

### PR DESCRIPTION
**Pull request by brinlyau**
Largely built on the shoulders of yrp's work.

### CODE REVIEW

**Comment by brinlyau** [comment]
Do you have a clang-format file, since I've been struggling with text inlining (I have 2 more patches for other stp/pac instructions)?

**Comment by brinlyau** [comment]
Needs more testing, out at the moment.

**Comment by lwerdna** [comment]
GetAllInstinsics() never returns your new instructions:

```
	virtual vector<uint32_t> GetAllIntrinsics() override
	{
		return vector<uint32_t> {ARM64_INTRIN_ISB};
        return vector<uint32_t> {ARM64_INTRIN_WFE};
        return vector<uint32_t> {ARM64_INTRIN_WFI};
	}
```

Don't re-issue the pull request, I need some practice with evaluating the pulls, editing them, then pushing back to master.

**Comment by lwerdna** [comment]
Tabs instead of spaces (not that I'm arguing one's better than the other, just to follow formatting conventions in whatever file you work in).

**Comment by lwerdna** [comment]
Thanks for the pull @brinlyau !!

**Pull request merged**
